### ISSUE TITLE
Goober not working with Gatsby v3?

### ISSUE THREAD

**Issue by wildpow** [cristianbote/goober#265] opened 2021-03-19 01:34 UTC
Getting an SSR is in development if SSR in development is enabled. If not dev works but builds fail.
<img width="747" alt="Screen Shot 2021-03-18 at 6 30 56 PM" src="https://user-images.githubusercontent.com/17464319/111718931-18b46400-8818-11eb-919a-f007bf4bc910.png">

Steps to reproduce
1. get a v3 starter like 'hello world' or 'default'
2. install `goober` and `gatsby-plugin-goober`
3.  add `gatsby-plugin-goober` to `gatsby-config.js`
4.  run `gatsby build`
5. fail :-(

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.1 => 3.1.1
    gatsby-plugin-gatsby-cloud: ^2.0.0 => 2.1.0
    gatsby-plugin-goober: ^2.3.1 => 2.3.1
    gatsby-plugin-image: ^1.0.0 => 1.1.1
    gatsby-plugin-manifest: ^3.0.0 => 3.1.0
    gatsby-plugin-offline: ^4.0.0 => 4.1.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.1.0
    gatsby-plugin-sharp: ^3.0.0 => 3.1.1
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.21 => 1.1.21
    gatsby-source-filesystem: ^3.0.0 => 3.1.0
    gatsby-transformer-sharp: ^3.0.0 => 3.1.0

**Comment by cristianbote** [comment] 2021-03-19 07:38
Hey @wildpow, thanks for opening this!

I can reproduce it as well. The problem is that apparently gatsby tries to load in a `node` env the `esm` version of the code, and `gatsby-plugin-goober` is written in `commonjs`. Once I changed the imports to `esm` seems to work fine. I still think there might be some weird exports map issue with gatsby, but it's an easy fix that can be done from our side. 👍

**Comment by cristianbote** [comment] 2021-03-19 07:44
Fixed in `gatsby-plugin-goober@2.4.0`

**Comment by cristianbote** [comment] 2021-03-19 07:46
@wildpow let me know if it's all good, when you got a second. Thanks again for opening this up!

**Closed** 2021-03-19 07:46 UTC
Labels: bug

**Comment by wildpow** [comment] 2021-03-19 07:48
Thank you, sir. You are a gentleman and a scholar.
